version: '3'
services:
  cervisia:
    image: n3phtys/cervisia-container:latest
    restart: always
    env_file: ./.docker/local.env
    ports:
     - "9080:8080"
    volumes:
     - ./db:/db
    command: sh -c "sh /db/load_json.sh && /usr/cervisia/backend/cervisia-server"
