version: '3'
services:
  cervisia:
    build: 
      context: .
      dockerfile: n3phtys/cervisia-container:avh-ka-deployment
    env_file: ./.docker/local.env
    ports:
     - "9080:8080"
    volumes:
     - ./db:/db
    command: sh /db/load_json.sh && /usr/cervisia/backend/cervisia-server
